main: me.saiintbrisson.minecraft.InventoryFramework
name: InventoryFramework
version: @version@
authors: [SaiintBrisson, DevNatan, sasuked]
website: https://github.com/DevNatan/inventory-framework
description: Bukkit Inventory API framework

commands:
  if:
    description: Opens the if