name: Publish Snapshot

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
        steps:
            - name: Checkout Application Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0

            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: '21'
                  distribution: 'temurin'
                  server-id: github
                  settings-path: ${{ github.workspace }}

            - name: Set up Gradle
              uses: gradle/actions/setup-gradle@v4

            - name: Publish Snapshot to Maven Central
              run: ./gradlew publishAndReleaseToMavenCentral --no-daemon --stacktrace --no-configuration-cache
              env:
                  ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.OSSRH_USERNAME }}
                  ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.OSSRH_TOKEN }}